[package]
name = "word-unscrambler"
version = "0.1.0"
edition = "2021"

[dependencies]
actix-web = "4"
regex = "1.10.6"
color-eyre = "0.6"
actix-files = "0.6.6"
lazy_static = "1.5.0"
serde_json = "1.0.132"
serde = { version = "1.0.210", features = ["derive"] }
num_cpus = "1.16.0"
